### ISSUE TITLE
Don't publish your .eslintrc

### ISSUE THREAD

**Issue by alasdairhurst** [cypress-io/xvfb#11]
Your .eslintrc file (as a transient dependency from cypress) has started to get picked up by my eslint run and killed CI.

![image](https://user-images.githubusercontent.com/8441810/46222001-eb715400-c346-11e8-9df2-6fe686e2cd25.png)

**Comment by alasdairhurst** [comment]
![image](https://user-images.githubusercontent.com/8441810/46222353-e6f96b00-c347-11e8-8725-2d8884062d89.png)
Looks like your other development stuff got published too. This is on 1.2.3. That version seems to have got lost on master here since you're back to 0.0.0-development

**Comment by alasdairhurst** [comment]
Thanks. Just downloaded the released artefact and it no longer has test/travis/eslint etc...
The problem now is that it still gets picked up since cypress has 1.2.3 hardcoded.

Not sure why this suddenly appeared as an issue though... It was all working perfectly earlier today and 1.2.3 has been out for a good 5 months.

**Comment by bahmutov** [comment]
What!!! That is so weird then, how can it overwrite existing version

**Comment by alasdairhurst** [comment]
Oh maybe you misunderstood :)
1.2.4.tgz looks good
1.2.3.tgz has all the dev stuff in, but is hardcoded in cypress

Unless you mean that somehow 1.2.3 could have got overridden which seems pretty strange if it did given that npm doesn't let you override versions!

**Comment by bahmutov** [comment]
Yeah I think 1.2.3 has always had all files

**Comment by alasdairhurst** [comment]
You're right. Looks like the issue is with some dependency of eslint. I just noticed now after removing the cypress dependency i get:
cannot find module '@satazor/eslint-config/addons/node'
Referenced from: C:\git\app\node_modules\npm\node_modules\err-code\.eslintrc.json

Thanks for cleaning up your dev stuff though. Hopefully cypress will get a bump soon with the changes, and hopefully eslint will get fixed :)

**Comment by bahmutov** [comment]
kk
