### ISSUE TITLE
How can I change screen size?

### ISSUE THREAD

**Issue by arjunkomath** [cypress-io/xvfb#52]
Is it possible to pass the screen argument:
`Xvfb :99 -ac -screen 0, 1680x1050x24 &`

I tried the following, but its not working
```
const xvfb = new XVFB({
	xvfb_args: ['-screen', '0, 1280x1024x24']
})
```

**Comment by arjunkomath** [comment]
Found the solution :)

**Comment by Kagenuge** [comment]
Well what was the solution then? :)

**Comment by syabro** [comment]
@arjunkomath could you please share the solution?

**Comment by arjunkomath** [comment]
This worked for me:
```javascript
const xvfb = new XVFB({
    xvfb_args: ['-dpi', 72, '-screen', 0, `${width}x${height}x24`]
})
```
